UsePercentage: true
Value: 1.0

Messages:
    Money_was_taken_from_your_account: '<money> was taken from your account because you died.'
    You_does_not_have_enough_money: 'Can not take money from your account because you not have enough money.'
    You_does_not_have_a_account: 'Can not take money from your account because you not have a account.'